### ISSUE TITLE
[BUG] In live preview, if @citekey is in bracket, tooltip doesn't show

### ISSUE THREAD

**Issue by Lisandra-dev** [mgmeyers/obsidian-pandoc-reference-list#31]
Tooltip doesn't show up if I add **one** pair of brackets around the @citekey. 
- Removing the bracket read the tooltip
- Adding `:` at the end of the [@citekey] too
- Tooltip work as intended in reading view

**Comment by mgmeyers** [comment]
@Mara-Li Could you share screenshots of what you're seeing?

**Comment by cyddgh** [comment]
Hi, @mgmeyers. I also meet a similar problem after upgrading the last version, as follow. 

![image](https://user-images.githubusercontent.com/10444611/168155897-1b617e7e-f004-4f17-b416-8d83cbab0155.png)

Bib path is "D:\mybib.bib".

![image](https://user-images.githubusercontent.com/10444611/168156113-cde17c68-1135-4093-8ccb-512852b3acd6.png)

Pandoc upgrade to 2.18.

![image](https://user-images.githubusercontent.com/10444611/168156723-5dab041e-0435-4e10-a7a7-cb116370ef34.png)

**Comment by mgmeyers** [comment]
@cyddgh what does the output HTML look like when you run:

`pandoc -f markdown -t html --citeproc --bibliography=D:\mybib.bib -o out.html path_to_202205122138test.md`

**Comment by cyddgh** [comment]
> @cyddgh what does the output HTML look like when you run:
> 
> `pandoc -f markdown -t html --citeproc --bibliography=D:\mybib.bib -o out.html path_to_202205122138test.md`

I run it, but failure.
```
C:\Program Files\Pandoc>pandoc -f markdown -t html --citeproc --bibliography=D:\mybib.bib -o out.html 202205122138test.md
Error reading bibliography file D:\mybib.bib:
(line 3491, column 33):
unexpected 'A'
```
In my bib file, this line has spaces. I fixed this problem and then success. Everything is go well. 
Thank you for your helping. This plugin is so useful for academics.

**Comment by Mara-Li** [comment]
Well, on my side I don't have problem during export with using the command for html (and export to docx works well too). 

My bug is a little different because I have the reference on the side of Obsidian : 
![image](https://user-images.githubusercontent.com/30244939/168233370-2d77e450-bca6-4458-9585-ea1c8d5e8d6b.png)
But no tooltip : 
![image](https://user-images.githubusercontent.com/30244939/168233418-9b68a2b6-8f62-4295-ac18-8b3ca8d15d45.png)
Unless I use the reading view : 
![image](https://user-images.githubusercontent.com/30244939/168233571-1d553c59-de91-4c48-8336-0d0f024366ae.png)

**Comment by mgmeyers** [comment]
Is this still an issue @Lisandra-dev ? Citekeys are processed much differently now in the latest version of the plugin.

**Comment by Lisandra-dev** [comment]
Hello!
I'm sorry; I don't use the plugin anymore as I finished my master and don't need pandoc :)
