### ISSUE TITLE
Plugin is wrongly applied to markdown links with `@`as well

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-pandoc-reference-list#35]
<img width="1004" alt="Pasted image 2022-05-31 13 13 58" src="https://user-images.githubusercontent.com/73286100/171161098-4b5f6d2d-b3c6-4911-be92-82a27c3abc9f.png">

Essentially, the plugins seems to be applied to as soon as there is an `@`. However, as in the example shown above, the case where I cite someone from Discord (or from Twitter), also has the `[@name]` syntax. But as opposed to pandoc citations, those are always followed by `(link)`, so this is actually an unequivocal case for the plugin to *not* consider something a pandoc citation. 

And given that many ppl cite someone from Twitter or Discord, this issue should also come up fairly often enough to warrant a general fix for the plugin (as opposed to simply someone fixing it via css snippet)

**Comment by mgmeyers** [comment]
This is a bit of a challenging scenario @chrisgrieser, and relates to #34. In my vault, I have literature notes named `@citekey.md` that I link to using `[[@citekey]]`, and I'd like the citation tooltip to show for these. It is possible, however, for users to set obsidian to use markdown links rather than wikilinks, meaning I would instead do `[@citekey](/path/to/@citekey.md)`. I'm not quite sure what the ideal solution would be here. I'll have to think on it a bit.

**Comment by chrisgrieser** [comment]
Yeah, I am too much of a coward to ever put characters like @ into my file names, but true, I haven't thought of this scenario. Maybe simply add a toggle in the settings, so users toggle it, depending on whether they sue such files or not?

**Comment by danieltomasz** [comment]
Maybe exclusion mechanism per folder in settings or per file basis via yaml will be a workaround?

**Comment by mgmeyers** [comment]
There's now an option to disable cite key processing in links. Let me know if you run into any issues with it

**Comment by chrisgrieser** [comment]
thank you for all the recent improvements to the plugin <3
