### ISSUE TITLE
FR: Several potential Pandoc paths?

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-pandoc-reference-list#9]
A problem that @argenos also encountered:
when switching to a different device, the plugin (initially) does not work due to the different setting requirements.

#1 solved part of it, but I noticed that on my second device, pandoc is being installed to a different location. Is is possible to maybe name multiple path where the plugin checks if pandoc is there? Or let the plugin simply always use the result of `which pandoc`, and requiring entering the pandoc path only as fallback?

**Comment by mgmeyers** [comment]
@chrisgrieser Unfortunately `which pandoc` will not always work because of some quirks related to executing things from an electron app. Let me see if I can figure out a way to do this.

And, just to be clear, are you referring to running this plugin in a single vault that's synced to multiple devices?

**Comment by mgmeyers** [comment]
Ok, by default, this plugin will attempt to find pandoc with `which`, but will use the supplied path if that fails
